robo_adviser/adviser/urls.py
from django.urls import path,include
from . import views
from .apis import table_data,chart_data, portfolio_chart_div
from django.contrib.auth import views as auth_views

app_name = 'adviser'
urlpatterns = [
    path('', views.start, name='start'),

    # ROUTER
    path('plot_result/', views.go_to_plot_result, name='go_to_plot_result'),
    path('table_result/',views.go_to_table_result, name='go_to_table_result'),

    path('multistrategy_result/', views.go_to_multistrategy_result, name='go_to_multistrategy_result'),
    # DEBUG FOR FORM2
    path('debuger_result1/', views.debuger_result1, name='debuger_result1'),

    # SHOW TABLE RESULT
    path('macd_table_result/', views.macd_table_result, name='macd_table_result'),
    path('rsi_table_result/', views.rsi_table_result, name='rsi_table_result'),
    path('ma_table_result/', views.ma_table_result, name='ma_table_result'),
    path('bb_table_result/', views.bb_table_result, name='bb_table_result'),

    path('bbandma_table_result/', views.bbandma_table_result, name='bbandma_table_result'),
    path('smawma_table_result/', views.smawma_table_result, name='smawma_table_result'),
    # path('r_strategy_result/', views.r_strategy_result, name='r_strategy_result'),

    # SHOW PLOT RESULT
    path('macd_plot_result/', views.macd_plot_result, name='macd_plot_result'),
    path('rsi_plot_result/', views.rsi_plot_result, name='rsi_plot_result'),
    path('ma_plot_result/', views.ma_plot_result, name='ma_plot_result'),
    path('bb_plot_result/', views.bb_plot_result, name='bb_plot_result'),

    # PORTFOLIO CHART
    path('portfolio_markowitz_result/', views.portfolio_markowitz_result, name='portfolio_markowitz_result'),
    path('portfolio_riskparity_result/', views.portfolio_riskparity_result, name='portfolio_riskparity_result'),
    path('portfolio_cvar_result/', views.portfolio_cvar_result, name='portfolio_cvar_result'),


    # API CHART DATA
    # path('api/chart/from_r/return', chart_data.StrategyFromRReturnData.as_view(), name="api_chart_return_data"),
    path('api/macd/chart/all', chart_data.StrategyMACDChartData.as_view(), name="api_macd_chart_data"),
    path('api/rsi/chart/all', chart_data.StrategyRSIChartData.as_view(), name="api_rsi_chart_data"),
    path('api/bb/chart/all', chart_data.StrategyBBChartData.as_view(), name="api_bb_chart_data"),
    path('api/ma/chart/all', chart_data.StrategyMAChartData.as_view(), name="api_ma_chart_data"),

    # API TABLE DATA
    # path('api/macd/chart/plot', chart_plot.StrategyMACDChartPlot.as_view(), name="api_macd_chart_plot"),
    path('api/macd/table/all', table_data.StrategyMACDTableData.as_view(), name="api_macd_table_data"),
    path('api/rsi/table/all', table_data.StrategyRSITableData.as_view(), name="api_rsi_table_data"),
    path('api/bb/table/all', table_data.StrategyBBTableData.as_view(), name="api_bb_table_data"),
    path('api/ma/table/all', table_data.StrategyMATableData.as_view(), name="api_ma_table_data"),

    path('api/smawma/table/all', table_data.StrategySMAWMATableData.as_view(), name="api_smawma_table_data"),
    path('api/bbandma/table/all', table_data.StrategyBBandMATableData.as_view(), name="api_bbandma_table_data"),

    # API PORTFOLIO CHART
    path('api/markowitz/chart/all', portfolio_chart_div.PortfolioMarkowitzChartData.as_view(), name="api_markowitz_chart_data"),
    path('api/riskparity/chart/all', portfolio_chart_div.PortfolioRiskParityChartData.as_view(), name="api_riskparity_chart_data"),
    path('api/cvar/chart/all', portfolio_chart_div.PortfolioCVaRChartData.as_view(), name="api_cvar_chart_data"),



]

robo_adviser/login/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('', views.showHomePage,name='home'),
    path("", views.login, name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('social-auth/', include('social_django.urls', namespace="social")),
    # path("", views.home, name="home"),
]

robo_adviser/questionnaire/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
app_name = 'questionnaire'
urlpatterns = [
    path('', views.start,name='start'),
    path("singleStrategyForm", views.singleStrategyForm, name="singleStrategyForm"),
    path("multiStrategyForm", views.multiStrategyForm, name="multiStrategyForm"),

    path("form2", views.form2, name="form2"),
    path('api/chart/data',views.TargetChartData.as_view(),name="api_target_chart_data"),
]

robo_adviser/robo_adviser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include('login.urls')),
    path('questionnaire/', include('questionnaire.urls')),
    path('adviser/', include('adviser.urls')),

]

robo_adviser/questionnaire/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView

import requests,sys,os
import pandas as pd

# from robo_adviser .adviser.indicators_factory import data_generator
from pandas_datareader import data as web
import datetime as dt
import yfinance as yf


yf.pdr_override()



# some how i cant do from robo_adviser.adviser.indicators_factory.data_generator import get_history_data
# to be solved
# https://stackoverflow.com/questions/46444135/how-to-import-models-from-one-app-to-another-app-in-django
def get_history_data(target,startdate= dt.datetime(2015, 1, 1),enddate= dt.datetime(2020, 1, 1)):
    print("get_history_data", target)
    can_call_api = ["1476", "2317", "2327", "2330", "2448", "2454", "2455", "2474", "2492",
                    "2498", "3019", "3037", "3406", "3443", "6153"]
    can_call_api = [codestr + ".TW" for codestr in can_call_api]
    # if (target in can_call_api):
    try:
        print("call mark web api")
        # payload = {'STOCK_ID': target[:4], 'KLINE_PERIOD': 'DAY', 'KLINE_DATETIME_S': '2019/05/08 09:10:00',
        #            'KLINE_DATETIME_E': '2020/01/01 12:00:00'}
        # response = requests.post("http://www.xiqicapital.com/FUT/Api/Market/QryStockPrice", params=payload)
        payload = {'STOCK_ID': target[:4], 'KLINE_PERIOD': 'DAY', 'KLINE_DATETIME_S': '2015/01/01 00:00:00',
                   'KLINE_DATETIME_E': '2020/01/01 12:00:00'}
        response = requests.post("http://www.xiqicapital.com/FUT/Api/Market/QryStockPrice2", params=payload)
        response_dic = response.json()
        result_df = pd.DataFrame.from_dict(response_dic['GridData'])
        result_df = result_df.set_index("KLINE_DATETIME")
        result_df = result_df.drop(axis=0, columns=["STOCK_ID", "KLINE_PERIOD"]).astype(float)
        result_df.columns = ['Close', 'High', 'Low', 'Open', 'Volume']
        result_df.index = pd.DatetimeIndex(result_df.index.rename("Date"))
    except:
        print("call yahoo finance")
        result_df = web.get_data_yahoo([target], startdate, enddate)
    return (result_df)


def get_stock_list():
    payload = {}
    response = requests.post("http://www.xiqicapital.com/FUT/Api/Market/QryStocList2", params=payload)
    response_dic = response.json()
    stock_list_df = pd.DataFrame(response_dic['GridData'])
    stock_id = stock_list_df['STOCK_ID']
    return(stock_list_df,stock_id)



def start(request):
    return(render(request,'enter_questionnaire.html'))

def singleStrategyForm(request):

    _, stock_list = get_stock_list()
    strategy_list = ["macd" , "rsi", 'bb', 'ma']
    stock_list = [strr+".TW" for strr in stock_list]
    context = {
        "stock_list":stock_list,
        "strategy_list":strategy_list,
    }
    return(render(request, "singleStrategyForm.html",context))


def multiStrategyForm(request):

    _, stock_list = get_stock_list()
    strategy_list = ["macd" , "rsi", 'bb', 'ma']
    portfolio_list = ["Markowitz", "RiskParity","CVaR"]
    stock_list = [strr+".TW" for strr in stock_list]
    context = {
        "stock_list":stock_list,
        "strategy_list":strategy_list,
        "portfolio_list": portfolio_list,
    }
    return(render(request, "multiStrategyForm.html",context))

def form2(request):
    # strategyList = ["macd" , "rsi", 'bb', 'ma']
    _, stock_list = get_stock_list()
    strategyList = ["macd", "rsi", 'bb', 'ma']
    stockList = [strr + ".TW" for strr in stock_list][:10]
    context = {
        "stockList": stockList,
        "strategyList": strategyList,
    }

    return(render(request, "form2.html", context))

#
class TargetChartData(APIView):
    def get(self, request, format = None):
        user_picked = request.GET['user_picked']
        df = get_history_data(user_picked)
        article_data=df.index
        article_labels=df.Close
        data={
            "article_data" : article_data,
            "article_labels" : article_labels
        }
        return(Response(data))

robo_adviser/questionnaire/templates/enter_questionnaire.html
{% extends "questionnaire_base.html" %}
{% load static %}
{% block contentInHead %}

<!-- Custom styles for this template -->


{% endblock %}
{% block questionnaireContent%}

<div class="container">
    <div class="row">
        <div class="card">
            <div class="card-body">we are going to ask a series of questions now get prepared</div>
        </div>
    </div>

</div>

{% endblock %}

robo_adviser/questionnaire/templates/form1.html
{% extends "questionnaire_base.html" %}
{% load static %}


{% block contentInHead %}

{% endblock %}

{% block questionnaireContent %}
<div class="container">
    <div class="row">
        <form name='myform'  method="GET">
            <div class="row">
                <div class="col-10 form-group">
                    <label class="custom-label custom-label-lg" for="stockpicker"> <h4>Pick a stock bro </h4> </label>
                    <select class="browser-default  custom-select custom-select-lg " name="stockpicker" id="stockpicker" >
                        {% for a_stock in stock_list %}
                           <option >{{a_stock}}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col-10 form-group" hidden>
                    <label class="custom-label custom-label-lg" for="strategypicker">Pick a stock bro</label>
                    <select class="browser-default  custom-select custom-select-lg " name="strategypicker" id="strategypicker" >
                        {% for a_stock in stock_list %}
                           <option >{{a_stock}}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col-12">
                    <div class="btn-group btn-group">
                        <button class= "btn" type="submit" name="action" value="smawma_result" formaction="{% url 'adviser:smawma_result' %}" >smawma</button>
                        <button class= "btn" type="submit" name="action" value="bbandma_result" formaction="{% url 'adviser:bbandma_result' %}">bbandma</button>
                        <button class= "btn" type="submit" name="action" value="macd_result" formaction="{% url 'adviser:macd_result' %}">macd_result</button>
                        <button class= "btn" type="submit" name="action" value="rsi_result" formaction="{% url 'adviser:rsi_result' %}">rsi_result</button>
                        <button class= "btn" type="submit" name="action" value="macd_plot_result" formaction="{% url 'adviser:macd_plot_result' %}">macd_plot_result</button>
                        <button class= "btn" type="submit" name="action" value="rsi_plot_result" formaction="{% url 'adviser:rsi_plot_result' %}">rsi_plot_result</button>

                    </div>
                </div>


            </div>
        </form>
    </div>
    <div class="row" id="line_fig">

    </div>
</div>

</div>

{% endblock %}

{% block contentJS %}
    <script>

        //solve the thing that Disabled form elements are not sent by the form.
        //$(':disabled').each(function(){
        //    $(this).after('<input type="hidden" name="' + $(this).attr('name') + '" value="' + $(this).val() + '" />');
        //});

        //開啟的時候就先畫圖
        $(document).ready(function(){
            var endpoint = 'api/chart/data'
            var articleData =  articleLabels = []
            $.ajax({
                method:"GET",
                url:endpoint,
                data:{
                    user_picked: $('#stockpicker').val()
                },
                success:function(data){
                    articleLabels = data.article_labels;
                    articleData = data.article_data;
                    prepareChart();

                },
                error:function(e){
                    alert(e);
                }
            });
            function prepareChart(){
                var trace1 = {
                    mode: 'lines',
                    x: articleData,
                    y: articleLabels,

                };
                var data = [ trace1 ];

                var layout = {
                  title:$('#stockpicker').val()
                };

                Plotly.newPlot('line_fig', data, layout);
            };
        });

        //換標的的時候畫圖
        $('#stockpicker').change(function(){

            var endpoint = 'api/chart/data'
            var articleData =  articleLabels = []

            $.ajax({
                method:"GET",
                url:endpoint,
                data:{
                    user_picked: $('#stockpicker').val()
                },
                success:function(data){
                    articleLabels = data.article_labels;
                    articleData = data.article_data;
                    prepareChart();

                },
                error:function(e){
                    console.log(e);
                }
            });

            function prepareChart(){
                var trace1 = {
                    mode: 'lines',
                    x: articleData,
                    y: articleLabels,

                };
                var data = [ trace1 ];

                var layout = {
                  title:$('#stockpicker').val()
                };

                Plotly.newPlot('line_fig', data, layout);
            };
        });
    </script>

{% endblock %}

robo_adviser/questionnaire/templates/form2.html
{% extends "questionnaire_base.html" %}
{% load static %}


{% block contentInHead %}
      <!-- Custom styles for this template -->
    <link href="{% static 'css/responsive_table_input_matrix.css'%}" rel="stylesheet">
    <link href="{% static 'css/awesome_bootstrap_checkbox.css'%}" rel="stylesheet">


{% endblock %}

{% block questionnaireContent %}
<div class="container ">
    <div class="row">
        <div class="col-6">
            <h3>pick multiple strategy and stock set</h3>
        </div>

    </div>
    <div class="row">
        <div class="col-10">
            <form  name='tablefform' action= "{% url 'adviser:debuger_result1' %}" method="GET">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th></th>
                                {% for aStrategy in strategyList %}
                                <th>{{ aStrategy }}</th>
                                {% endfor %}
                            </tr>
                        </thead>
                        <tbody>

                        {% for aStock in stockList %}
                        <tr>
                            <td>{{ aStock }}</td>
                            {% for aStrategy in strategyList %}
                            <td>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" name="target_strategy" id="{{ aStock }}_{{ aStrategy }}" value="{{ aStock }}_{{ aStrategy }}">
                                    <label class="custom-control-label" for="{{ aStock }}_{{ aStrategy }}"></label>
                                </div>
                            </td>
                            {% endfor %}
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                    <input class="btn btn-primary" type="submit" value="enter">
                    <input class="btn btn-dark" type="reset" value="reset">

            </form>

        </div>
    </div>
</div>


{% endblock %}
{% block contentJS %}
    <!-- JQuery -->
<!--    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>-->
<!--    &lt;!&ndash; Bootstrap tooltips &ndash;&gt;-->
<!--    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>-->
<!--    &lt;!&ndash; Bootstrap core JavaScript &ndash;&gt;-->
<!--    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>-->
<!--    &lt;!&ndash; MDB core JavaScript &ndash;&gt;-->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/js/mdb.min.js"></script>
{% endblock %}

robo_adviser/questionnaire/templates/questionnaire_base.html
{% extends "base.html" %}

{% load static %}

{% block contentInHead %}

  <!-- Bootstrap for this one -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <!-- Custom styles for this template -->


{% endblock %}

{%block contentInBody%}
  <!--such a fucking weird thing that this link has to put it in here that it will work -->
  <link href="{% static 'css/simple-sidebar.css'%}" rel="stylesheet">
  <div class="d-flex" id="wrapper">


    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading"><h3>Welcome Dude</h3> </div>
      <div class="list-group list-group-flush">
        <a href="{% url 'questionnaire:start' %}" class="list-group-item list-group-item-action bg-light">start</a>
        <a href="{% url 'questionnaire:singleStrategyForm' %}" class="list-group-item list-group-item-action bg-light">single target strategy</a>
        <a href="{% url 'questionnaire:multiStrategyForm' %}" class="list-group-item list-group-item-action bg-light">multiStrategyForm</a>

        <a href="{% url 'questionnaire:form2' %}" class="list-group-item list-group-item-action bg-light">test form for the future</a>

      </div>
    </div>


    <div id="page-content-wrapper">
      <div class="container-fluid">
    {% block questionnaireContent%}

    {% endblock %}
      </div>
    </div>



  </div>
{% endblock %}




<!--{% block contentJS %}-->
<!--  &lt;!&ndash; Menu Toggle Script &ndash;&gt;-->
<!--  <script>-->
<!--    $("#menu-toggle").click(function(e) {-->
<!--      e.preventDefault();-->
<!--      $("#wrapper").toggleClass("toggled");-->
<!--    });-->
<!--  </script>-->


<!--{% endblock %}-->

robo_adviser/questionnaire/templates/singleStrategyForm.html
{% extends "questionnaire_base.html" %}
{% load static %}


{% block contentInHead %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}

{% block questionnaireContent %}
<div class="container">
    <div class="row">
        <div class="col-12 panel ">

            <form name='myform'  method="GET">
                <div class="row">
                    <div class="col-12 card border-light">
                        <div class="card-body">
                            <div class="col-8">
                                <div class="form-group form-inline">
                                    <div class="col-6">
                                        <div class="md-form">
                                            <input class = "form-control" type="text" id = "from_date" name="from_date" value="01/01/2015" />
                                            <label class="" for="from_date"> FROM DATE </label>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="md-form">
                                            <input class="form-control" type="text" id = "to_date" name="to_date" value="" />
                                            <label class="" for="to_date"> TO DATE </label>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group form-inline">
                                    <div class="col-6">
                                        <div class="md-form">
                                            <input class = "form-control" type="number" id = "capital" name="capital" value=100000 />
                                            <label class="" for="from_date"> CAPITAL </label>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="md-form">
                                            <input class="form-control" type="number" id = "leverage" name="leverage" value=1 />
                                            <label class="" for="leverage"> LEVERAGE </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group md-form" hidden>
                                    <label class=""> TARGET TYPE </label><br><br>
                                    <select class="selectpicker " name="typepicker" id="typepicker" data-width="100%">
                                        <option >Stock</option>
                                        <option >Futures</option>
                                        <option >Option</option>
                                    </select>
                                </div>
                                <div class="form-group md-form selectpicker-div" >
                                    <label class=""> STRATEGY </label><br><br>
                                    <select class="selectpicker " name="strategypicker" id="strategypicker" data-width="100%" >
                                        {% for a_strategy in strategy_list %}
                                           <option value ="{{a_strategy}}">{{a_strategy.upper}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group md-form selectpicker-div">
                                    <label class=""> ASSET </label><br><br>
                                    <select class="selectpicker " name="stockpicker" id="stockpicker" data-live-search="true" data-width="100%" data-size="8">
                                        {% for a_stock in stock_list %}
                                           <option>{{a_stock}}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <button class="btn btn-light" type="reset">reset</button>
                                <button class= "btn btn-primary" type="submit" name="action" value="go_to_table_result" formaction="{% url 'adviser:go_to_table_result' %}">table result</button>
                                <button class= "btn btn-primary" type="submit" name="action" value="go_to_plot_result" formaction="{% url 'adviser:go_to_plot_result' %}">plot result</button>
<!--                                <button class= "btn btn-primary" type="submit" name="action" value="macd_plot_result" formaction="{% url 'adviser:macd_plot_result' %}">macd_plot_result</button>-->
                            </div>
                        </div>
                        <div class="card-footer bg-transparent ">
                            <div class="row" id="line_fig"></div>
                        </div>
                    </div>


                </div>

            </form>
        </div>
    </div>

</div>

</div>

{% endblock %}

{% block contentJS %}

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
<!-- (Optional) Latest compiled and minified JavaScript translation files -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/i18n/defaults-*.min.js"></script>
<!--daterange picker cdn-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>


    <script>
    $(function() {
      $('input[name="from_date"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        minYear: 2015,
        maxYear: parseInt(moment().format('YYYY'),10)
      });
    });
    $(function() {
      $('input[name="to_date"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        minYear: 2015,
        maxYear: parseInt(moment().format('YYYY'),10)
      });
    });
    </script>

    <script>


        //solve the thing that Disabled form elements are not sent by the form.
        //$(':disabled').each(function(){
        //    $(this).after('<input type="hidden" name="' + $(this).attr('name') + '" value="' + $(this).val() + '" />');
        //});

        //開啟的時候就先畫圖
        $(document).ready(function(){
            var endpoint = 'api/chart/data'
            var articleData =  articleLabels = []
            $.ajax({
                method:"GET",
                url:endpoint,
                data:{
                    user_picked: $('#stockpicker').val()
                },
                success:function(data){
                    articleLabels = data.article_labels;
                    articleData = data.article_data;
                    prepareChart();

                },
                error:function(e){
                    alert(e);
                }
            });
            function prepareChart(){
                var trace1 = {
                    mode: 'lines',
                    x: articleData,
                    y: articleLabels,

                };
                var data = [ trace1 ];

                var layout = {
                  title:$('#stockpicker').val()
                };

                Plotly.newPlot('line_fig', data, layout);
            };
        });

        //換標的的時候畫圖
        $('#stockpicker').change(function(){

            var endpoint = 'api/chart/data'
            var articleData =  articleLabels = []

            $.ajax({
                method:"GET",
                url:endpoint,
                data:{
                    user_picked: $('#stockpicker').val()
                },
                success:function(data){
                    articleLabels = data.article_labels;
                    articleData = data.article_data;
                    prepareChart();

                },
                error:function(e){
                    console.log(e);
                }
            });

            function prepareChart(){
                var trace1 = {
                    mode: 'lines',
                    x: articleData,
                    y: articleLabels,

                };
                var data = [ trace1 ];

                var layout = {
                  title:$('#stockpicker').val()
                };

                Plotly.newPlot('line_fig', data, layout);
            };
        });
    </script>

{% endblock %}