robo_adviser/adviser/urls.py
from django.urls import path,include
from . import views
from .apis import table_data,chart_data, portfolio_chart_div
from django.contrib.auth import views as auth_views

app_name = 'adviser'
urlpatterns = [
    path('', views.start, name='start'),

    # ROUTER
    path('plot_result/', views.go_to_plot_result, name='go_to_plot_result'),
    path('table_result/',views.go_to_table_result, name='go_to_table_result'),

    path('multistrategy_result/', views.go_to_multistrategy_result, name='go_to_multistrategy_result'),
    # DEBUG FOR FORM2
    path('debuger_result1/', views.debuger_result1, name='debuger_result1'),

    # SHOW TABLE RESULT
    path('macd_table_result/', views.macd_table_result, name='macd_table_result'),
    path('rsi_table_result/', views.rsi_table_result, name='rsi_table_result'),
    path('ma_table_result/', views.ma_table_result, name='ma_table_result'),
    path('bb_table_result/', views.bb_table_result, name='bb_table_result'),

    path('bbandma_table_result/', views.bbandma_table_result, name='bbandma_table_result'),
    path('smawma_table_result/', views.smawma_table_result, name='smawma_table_result'),
    # path('r_strategy_result/', views.r_strategy_result, name='r_strategy_result'),

    # SHOW PLOT RESULT
    path('macd_plot_result/', views.macd_plot_result, name='macd_plot_result'),
    path('rsi_plot_result/', views.rsi_plot_result, name='rsi_plot_result'),
    path('ma_plot_result/', views.ma_plot_result, name='ma_plot_result'),
    path('bb_plot_result/', views.bb_plot_result, name='bb_plot_result'),

    # PORTFOLIO CHART
    path('portfolio_markowitz_result/', views.portfolio_markowitz_result, name='portfolio_markowitz_result'),
    path('portfolio_riskparity_result/', views.portfolio_riskparity_result, name='portfolio_riskparity_result'),
    path('portfolio_cvar_result/', views.portfolio_cvar_result, name='portfolio_cvar_result'),


    # API CHART DATA
    # path('api/chart/from_r/return', chart_data.StrategyFromRReturnData.as_view(), name="api_chart_return_data"),
    path('api/macd/chart/all', chart_data.StrategyMACDChartData.as_view(), name="api_macd_chart_data"),
    path('api/rsi/chart/all', chart_data.StrategyRSIChartData.as_view(), name="api_rsi_chart_data"),
    path('api/bb/chart/all', chart_data.StrategyBBChartData.as_view(), name="api_bb_chart_data"),
    path('api/ma/chart/all', chart_data.StrategyMAChartData.as_view(), name="api_ma_chart_data"),

    # API TABLE DATA
    # path('api/macd/chart/plot', chart_plot.StrategyMACDChartPlot.as_view(), name="api_macd_chart_plot"),
    path('api/macd/table/all', table_data.StrategyMACDTableData.as_view(), name="api_macd_table_data"),
    path('api/rsi/table/all', table_data.StrategyRSITableData.as_view(), name="api_rsi_table_data"),
    path('api/bb/table/all', table_data.StrategyBBTableData.as_view(), name="api_bb_table_data"),
    path('api/ma/table/all', table_data.StrategyMATableData.as_view(), name="api_ma_table_data"),

    path('api/smawma/table/all', table_data.StrategySMAWMATableData.as_view(), name="api_smawma_table_data"),
    path('api/bbandma/table/all', table_data.StrategyBBandMATableData.as_view(), name="api_bbandma_table_data"),

    # API PORTFOLIO CHART
    path('api/markowitz/chart/all', portfolio_chart_div.PortfolioMarkowitzChartData.as_view(), name="api_markowitz_chart_data"),
    path('api/riskparity/chart/all', portfolio_chart_div.PortfolioRiskParityChartData.as_view(), name="api_riskparity_chart_data"),
    path('api/cvar/chart/all', portfolio_chart_div.PortfolioCVaRChartData.as_view(), name="api_cvar_chart_data"),



]

robo_adviser/login/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('', views.showHomePage,name='home'),
    path("", views.login, name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('social-auth/', include('social_django.urls', namespace="social")),
    # path("", views.home, name="home"),
]

robo_adviser/robo_adviser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include('login.urls')),
    path('questionnaire/', include('questionnaire.urls')),
    path('adviser/', include('adviser.urls')),

]

robo_adviser/adviser/models.py
from django.db import models

# Create your models here.

robo_adviser/adviser/views.py
from django.shortcuts import render,HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse

# self defined function for conveniency
def custom_redirect(url_name,  **kwargs):
    # from django.core.urlresolvers import reverse
    import urllib
    url = reverse(url_name)
    params = urllib.parse.urlencode(kwargs)
    return HttpResponseRedirect(url + "?%s" % params)

# start
def start(request):
    return(render(request,'enter_adviser.html',locals()))

# router
def go_to_plot_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = request.GET['strategypicker']
    except Exception:
        print("request.GET['stockpicker'] failed")
    print("we are in go_to_plot_result:", selected_target, selected_target)
    # print("we are in go_to_plot_result:", selected_target)
    redirect_target = reverse('adviser:{}_plot_result'.format(selected_strategy))
    return redirect("{}?stockpicker={}".format(redirect_target,selected_target))

def go_to_table_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = request.GET['strategypicker']
    except Exception:
        print("request.GET['stockpicker'] failed")

    print("we are in go_to_table_result:", selected_target)
    redirect_target = reverse('adviser:{}_table_result'.format(selected_strategy))
    return redirect("{}?stockpicker={}".format(redirect_target,selected_target))

# portfolio router
def go_to_multistrategy_result(request):
    selected_target = request.GET['stockpicker']
    selected_portfolio = request.GET['portfolio']
    selected_strategy = request.GET.getlist('strategypicker')
    return custom_redirect('adviser:portfolio_{}_result'.format(selected_portfolio.lower()), stockpicker = selected_target,strategypicker = selected_strategy)

# portfolio view
def portfolio_markowitz_result(request):
    import json
    selected_target = request.GET['stockpicker']
    selected_strategy_str = request.GET['strategypicker']
    selected_strategy_list = [aS.strip()[1:-1] for aS in selected_strategy_str[1:-1].split(',')]

    # 這裡這樣做是為了未來可以放進"多資產"的資產配置策略,目前只有單一資產多策略
    target_strategy = ["{}_{}".format(selected_target,aS) for aS in selected_strategy_list]
    context = {"selected_target": selected_target,
               "selected_strategy_str": selected_strategy_str,
               "target_strategy": json.dumps(target_strategy),
               "portfolio":"Markowitz",
               }
    return (render(request, "portfolio_markowitz_result.html",context=context))

def portfolio_riskparity_result(request):
    import json
    selected_target = request.GET['stockpicker']
    selected_strategy_str = request.GET['strategypicker']
    selected_strategy_list = [aS.strip()[1:-1] for aS in selected_strategy_str[1:-1].split(',')]

    # 這裡這樣做是為了未來可以放進"多資產"的資產配置策略,目前只有單一資產多策略
    target_strategy = ["{}_{}".format(selected_target,aS) for aS in selected_strategy_list]
    context = {"selected_target": selected_target,
               "selected_strategy_str": selected_strategy_str,
               "target_strategy": json.dumps(target_strategy),

               "portfolio": "RiskParity",
               }
    return (render(request, "portfolio_riskparity_result.html",context=context))

def portfolio_cvar_result(request):
    import json
    selected_target = request.GET['stockpicker']
    selected_strategy_str = request.GET['strategypicker']
    selected_strategy_list = [aS.strip()[1:-1] for aS in selected_strategy_str[1:-1].split(',')]

    # 這裡這樣做是為了未來可以放進"多資產"的資產配置策略,目前只有單一資產多策略
    target_strategy = ["{}_{}".format(selected_target,aS) for aS in selected_strategy_list]
    context = {"selected_target": selected_target,
               "selected_strategy_str": selected_strategy_str,
               "target_strategy": json.dumps(target_strategy),

               "portfolio": "CVaR",
               }
    return (render(request, "portfolio_cvar_result.html",context=context))

# single_target_result_using_ajax table view
def smawma_table_result(request):
    try:
        selected_target = request.GET['stockpicker']
    except:
        print("request.GET['stockpicker'] failed")
    context = {
        "selected_target": selected_target,
        "selected_strategy": "smawma",
    }
    return(render(request,"single_target_result_using_ajax.html", context))

def bbandma_table_result(request):
    try:
        selected_target = request.GET['stockpicker']
    except:
        print("request.GET['stockpicker'] failed")
    context = {
        "selected_target": selected_target,
        "selected_strategy": "bbandma",
    }
    return(render(request,"single_target_result_using_ajax.html", context))

# MACD
def macd_table_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = 'macd'
    except:
        print("error")
    return (render(request, 'macd_table_result.html', locals()))

def macd_plot_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = 'macd'
    except:
        print("error")
    return (render(request, 'macd_plotjs_result.html', locals()))

# RSI
def rsi_table_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = 'rsi'
    except:
        print("error")
    return (render(request, 'rsi_table_result.html', locals()))

def rsi_plot_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = 'rsi'
    except:
        print("error")
    return (render(request, 'rsi_plotjs_result.html', locals()))

def ma_table_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = 'ma'
    except:
        print("error")
    return (render(request, 'ma_table_result.html', locals()))

# MA
def ma_plot_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = 'ma'
    except:
        print("error")
    return (render(request, 'ma_plotjs_result.html', locals()))

def bb_table_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = 'bb'
    except:
        print("error")
    return (render(request, 'bb_table_result.html', locals()))

# BB
def bb_plot_result(request):
    try:
        selected_target = request.GET['stockpicker']
        selected_strategy = 'bb'
    except:
        print("error")
    return (render(request, 'bb_plotjs_result.html', locals()))


def debuger_result1(request):
    target_strategy = request.GET.getlist('target_strategy')
    pairs = [tuple(aPair.split("_")) for aPair in target_strategy]
    return (render(request, 'test/result1.html', locals()))


# def r_strategy_result(request):
#     try:
#         selected_target = request.GET['stockpicker']
#     except:
#         print("error")
#     return (render(request, 'r_strategy_result.html', locals()))

robo_adviser/adviser/templates/adviser_base.html
{% extends "base.html" %}
{% load static %}
{% block contentInHead %}
  <!-- Custom styles for this template -->

  <link href="{% static 'css/simple-sidebar.css'%}" rel="stylesheet">
  <!-- Latest compiled and minified CSS -->
<!--  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">-->
<!--  &lt;!&ndash; Latest compiled and minified JavaScript &ndash;&gt;-->
<!--  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>-->
<!--  &lt;!&ndash; (Optional) Latest compiled and minified JavaScript translation files &ndash;&gt;-->
<!--  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/i18n/defaults-*.min.js"></script>-->
<!--cdn bootstrap table-->
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.2/dist/bootstrap-table.min.css">
  <script src="https://unpkg.com/bootstrap-table@1.15.2/dist/bootstrap-table.min.js"></script>

{% endblock %}

{%block contentInBody%}

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">Yo I'm Super Smart </div>
      <div class="list-group list-group-flush">
        <a href="{% url 'adviser:start'  %}" class="list-group-item list-group-item-action bg-light">start</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">not function thing</a>

      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <div class="container-fluid">
  {% block resultContent %}




  {% endblock %}
    </div>
  </div>


{% endblock %}

robo_adviser/adviser/templates/bb_plotjs_result.html
{% extends "adviser_base.html" %}


{% block resultContent %}
<div class="container">
    <div class="row card">
        <div class="card-header">
            <h2>You have selected target {{selected_target}} and the strategy {{selected_strategy}}</h2>
        </div>
        <div class="card-body">
            <div class="col-12">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active" id="asset-tab" data-toggle="tab" href="#asset" role="tab" aria-controls="asset"
                      aria-selected="true">Trading Signal</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="assetReturn-tab" data-toggle="tab" href="#assetReturn" role="tab" aria-controls="assetReturn"
                      aria-selected="false">Asset Return</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="strategyReturn-tab" data-toggle="tab" href="#strategyReturn" role="tab" aria-controls="strategyReturn"
                      aria-selected="false">Strategy Return</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="strategyDrawDown-tab" data-toggle="tab" href="#strategyDrawDown" role="tab" aria-controls="strategyDrawDown"
                      aria-selected="false">Strategy Draw Down</a>
                  </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active col-12" id="asset" role="tabpanel" aria-labelledby="asset-tab">
                        <div class="col-12">
                            <div id="fig_price"></div>
                            <div id="loader_circle" class="spinner-border m-5" role="status">
                              <span class="sr-only">Loading...</span>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade col-12" id="assetReturn" role="tabpanel" aria-labelledby="assetReturn-tab">
                        <div class="col-12"><div id="fig_targetRet"></div></div>

                        <div class="col-12"><div id="fig_targetCumRet"></div></div>
                    </div>
                    <div class="tab-pane fade col-12" id="strategyReturn" role="tabpanel" aria-labelledby="strategyReturn-tab">
                        <div class="col-12"><div id="fig_strategyRet"></div></div>
                        <div class="w-100"></div>
                        <div class="col-12"><div id="fig_strategyCumRet"></div></div>
                    </div>
                    <div class="tab-pane fade col-12" id="strategyDrawDown" role="tabpanel" aria-labelledby="strategyDrawDown-tab">
                        <div class="col-12"><div id="fig_strategyDrawdowns"></div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}



{% block contentJS %}
<script>
    $(document).ready(function(){
        var endpoint = "{% url 'adviser:api_bb_chart_data' %}"
        var Date =  targetRet = targetCumRet = strategyRet = strategyDrawdowns = strategyCumRet = [];
        var price = buyDate = buyPrice = sellDate = sellPrice = [];
        $.ajax({
            method:"GET",
            url:endpoint,
            data:{
                selected_target:"{{selected_target}}"
            },
            success:function(data){
                Date = data.Date;
                targetRet = data.targetRet;
                targetCumRet = data.targetCumRet;
                strategyRet = data.strategyRet;
                strategyCumRet = data.strategyCumRet;
                strategyDrawdowns = data.strategyDrawdowns;

                price = data.price
                buyDate = data.buyDate;
                buyPrice = data.buyPrice;
                sellDate = data.sellDate;
                sellPrice = data.sellPrice;

                preparePriceChart();
                prepareChart(Date,targetRet,'fig_targetRet','targetRet');
                prepareChart(Date,targetCumRet,'fig_targetCumRet','targetCumRet');
                prepareChart(Date,strategyRet,'fig_strategyRet','strategyRet');
                prepareChart(Date,strategyDrawdowns,'fig_strategyDrawdowns','strategyDrawdowns');
                prepareChart(Date,strategyCumRet,'fig_strategyCumRet','strategyCumRet');

            },
            error:function(e){
                alert(e.msg);
            }
        });
        function preparePriceChart(){
            var PriceLine = {
                mode: 'lines',
                x: Date,
                y: price,
            };
            var BuyScatter = {
                mode: 'markers',
                type: 'scatter',
                x: buyDate,
                y: buyPrice,
            };
            var SellScatter = {
                mode: 'markers',
                type: 'scatter',
                x: sellDate,
                y: sellPrice,
            };
            var data = [ PriceLine , BuyScatter , SellScatter];
            var layout = {
              title:"Trading Signal"
            };
            Plotly.newPlot("fig_price", data, layout,{responsive: true});
        };

        function prepareChart(Date,Y,div_id,fig_name){
            var trace1 = {
                mode: 'lines',
                x: Date,
                y: Y,
            };
            var data = [ trace1 ];
            var layout = {
              title:fig_name,

            };
            Plotly.newPlot(div_id, data, layout,{responsive: true});
        };
    });
</script>
{% endblock %}

robo_adviser/adviser/templates/bb_table_result.html
{% extends "adviser_base.html" %}



{% block resultContent %}
<div class="container">
    <div class="row">
        <h2>you have selected target {{selected_target}} and the strategy {{selected_strategy}}</h2>
    </div>

    <div class="row">
       <div class="col-md-12"><div id="plot">{{plot|safe}}</div></div>
        <div id="result_table_html" class="col-10">
            <table id="datatable"></table>
        </div>

    </div>
    <div class="row">

    </div>

</div>


{% endblock %}
{% block contentJS%}

<script>
    $(document).ready(function(){

        $.ajax({
            url: "not yet",
            type: 'get',
            data:{
                selected_target:"{{selected_target}}"
            },
            success: function(data) {
                $('#plot').empty().append(data);
            },
            failure: function(data) {
                alert('Got an error dude!');

            },
            complete: function(data) {
                var message = 'Time: '+(new Date().getTime() - this.start_time);
                console.log(message);
            }
          });


        var endpoint = "{% url 'adviser:api_bb_table_data' %}"
        var selected_target = columns =  result_table_json = []
        $.ajax({
            method:"GET",
            url:endpoint,
            data:{
                selected_target:"{{selected_target}}"
            },
            success:function(data){
                selected_target=data.selected_target;
                result_table_dict=data.result_table_dict;
                columns = data.columns_dict;
                prepareTable();
            },
            error:function(e){
                alert(e.msg);
            }
        });
        function prepareTable(){
            $('#datatable').bootstrapTable({
                data:result_table_dict,
                columns:columns,
                striped: true,
                pagination: true,
                showColumns: true,
                showToggle: false,
                showExport: true,
                sortable: true,
                paginationVAlign: 'both',
                pageSize: 10,
                pageList: [10, 25, 50, 100, 'ALL'],
            });
        };



    });







</script>




{% endblock%}

robo_adviser/adviser/templates/ma_plotjs_result.html
{% extends "adviser_base.html" %}


{% block resultContent %}
<div class="container">
    <div class="row card">
        <div class="card-header">
            <h2>You have selected target {{selected_target}} and the strategy {{selected_strategy}}</h2>
        </div>
        <div class="card-body">
            <div class="col-12">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active" id="asset-tab" data-toggle="tab" href="#asset" role="tab" aria-controls="asset"
                      aria-selected="true">Trading Signal</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="assetReturn-tab" data-toggle="tab" href="#assetReturn" role="tab" aria-controls="assetReturn"
                      aria-selected="false">Asset Return</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="strategyReturn-tab" data-toggle="tab" href="#strategyReturn" role="tab" aria-controls="strategyReturn"
                      aria-selected="false">Strategy Return</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="strategyDrawDown-tab" data-toggle="tab" href="#strategyDrawDown" role="tab" aria-controls="strategyDrawDown"
                      aria-selected="false">Strategy Draw Down</a>
                  </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active col-12" id="asset" role="tabpanel" aria-labelledby="asset-tab">
                        <div class="col-12">
                            <div id="fig_price"></div>
                            <div id="loader_circle" class="spinner-border m-5" role="status">
                              <span class="sr-only">Loading...</span>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade col-12" id="assetReturn" role="tabpanel" aria-labelledby="assetReturn-tab">
                        <div class="col-12"><div id="fig_targetRet"></div></div>

                        <div class="col-12"><div id="fig_targetCumRet"></div></div>
                    </div>
                    <div class="tab-pane fade col-12" id="strategyReturn" role="tabpanel" aria-labelledby="strategyReturn-tab">
                        <div class="col-12"><div id="fig_strategyRet"></div></div>
                        <div class="w-100"></div>
                        <div class="col-12"><div id="fig_strategyCumRet"></div></div>
                    </div>
                    <div class="tab-pane fade col-12" id="strategyDrawDown" role="tabpanel" aria-labelledby="strategyDrawDown-tab">
                        <div class="col-12"><div id="fig_strategyDrawdowns"></div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}



{% block contentJS %}
<script>
    $(document).ready(function(){
        var endpoint = "{% url 'adviser:api_ma_chart_data' %}"
        var Date =  targetRet = targetCumRet = strategyRet = strategyDrawdowns = strategyCumRet = [];
        var price = buyDate = buyPrice = sellDate = sellPrice = [];
        $.ajax({
            method:"GET",
            url:endpoint,
            data:{
                selected_target:"{{selected_target}}"
            },
            success:function(data){
                Date = data.Date;
                targetRet = data.targetRet;
                targetCumRet = data.targetCumRet;
                strategyRet = data.strategyRet;
                strategyCumRet = data.strategyCumRet;
                strategyDrawdowns = data.strategyDrawdowns;

                price = data.price
                buyDate = data.buyDate;
                buyPrice = data.buyPrice;
                sellDate = data.sellDate;
                sellPrice = data.sellPrice;

                preparePriceChart();
                prepareChart(Date,targetRet,'fig_targetRet','targetRet');
                prepareChart(Date,targetCumRet,'fig_targetCumRet','targetCumRet');
                prepareChart(Date,strategyRet,'fig_strategyRet','strategyRet');
                prepareChart(Date,strategyDrawdowns,'fig_strategyDrawdowns','strategyDrawdowns');
                prepareChart(Date,strategyCumRet,'fig_strategyCumRet','strategyCumRet');

            },
            error:function(e){
                alert(e.msg);
            }
        });
        function preparePriceChart(){
            var PriceLine = {
                mode: 'lines',
                x: Date,
                y: price,
            };
            var BuyScatter = {
                mode: 'markers',
                type: 'scatter',
                x: buyDate,
                y: buyPrice,
            };
            var SellScatter = {
                mode: 'markers',
                type: 'scatter',
                x: sellDate,
                y: sellPrice,
            };
            var data = [ PriceLine , BuyScatter , SellScatter];
            var layout = {
              title:"Trading Signal"
            };
            Plotly.newPlot("fig_price", data, layout,{responsive: true});
        };

        function prepareChart(Date,Y,div_id,fig_name){
            var trace1 = {
                mode: 'lines',
                x: Date,
                y: Y,
            };
            var data = [ trace1 ];
            var layout = {
              title:fig_name,

            };
            Plotly.newPlot(div_id, data, layout,{responsive: true});
        };
    });
</script>
{% endblock %}

robo_adviser/adviser/templates/ma_table_result.html
{% extends "adviser_base.html" %}



{% block resultContent %}
<div class="container">
    <div class="row">
        <h2>you have selected target {{selected_target}} and the strategy {{selected_strategy}}</h2>
    </div>

    <div class="row">
       <div class="col-md-12"><div id="plot">{{plot|safe}}</div></div>
        <div id="result_table_html" class="col-10">
            <table id="datatable"></table>
        </div>

    </div>
    <div class="row">

    </div>

</div>


{% endblock %}
{% block contentJS%}

<script>
    $(document).ready(function(){

        $.ajax({
            url: "not yet",
            type: 'get',
            data:{
                selected_target:"{{selected_target}}"
            },
            success: function(data) {
                $('#plot').empty().append(data);
            },
            failure: function(data) {
                alert('Got an error dude!');

            },
            complete: function(data) {
                var message = 'Time: '+(new Date().getTime() - this.start_time);
                console.log(message);
            }
          });


        var endpoint = "{% url 'adviser:api_ma_table_data' %}"
        var selected_target = columns =  result_table_json = []
        $.ajax({
            method:"GET",
            url:endpoint,
            data:{
                selected_target:"{{selected_target}}"
            },
            success:function(data){
                selected_target=data.selected_target;
                result_table_dict=data.result_table_dict;
                columns = data.columns_dict;
                prepareTable();
            },
            error:function(e){
                alert(e.msg);
            }
        });
        function prepareTable(){
            $('#datatable').bootstrapTable({
                data:result_table_dict,
                columns:columns,
                striped: true,
                pagination: true,
                showColumns: true,
                showToggle: false,
                showExport: true,
                sortable: true,
                paginationVAlign: 'both',
                pageSize: 10,
                pageList: [10, 25, 50, 100, 'ALL'],
            });
        };



    });







</script>




{% endblock%}

robo_adviser/adviser/templates/macd_result.html
{% extends "adviser_base.html" %}



{% block resultContent %}
<div class="container">
    <div class="row">
        <h2>you have selected target {{selected_target}} and the strategy {{selected_strategy}}</h2>
    </div>

    <div class="row">
       <div class="col-md-12"><div id="plot">{{plot|safe}}</div></div>
        <div id="result_table_html" class="col-10">
            <table id="datatable"></table>
        </div>

    </div>
    <div class="row">

    </div>

</div>


{% endblock %}
{% block contentJS%}

<script>
    $(document).ready(function(){

        $.ajax({
            url: "not yet",
            type: 'get',
            data:{
                selected_target:"{{selected_target}}"
            },
            success: function(data) {
                $('#plot').empty().append(data);
            },
            failure: function(data) {
                alert('Got an error dude!');

            },
            complete: function(data) {
                var message = 'Time: '+(new Date().getTime() - this.start_time);
                console.log(message);
            }
          });


        var endpoint = "{% url 'adviser:api_macd_table_data' %}"
        var selected_target = columns =  result_table_json = []
        $.ajax({
            method:"GET",
            url:endpoint,
            data:{
                selected_target:"{{selected_target}}"
            },
            success:function(data){
                selected_target=data.selected_target;
                result_table_dict=data.result_table_dict;
                columns = data.columns_dict;
                prepareTable();
            },
            error:function(e){
                alert(e.msg);
            }
        });
        function prepareTable(){
            $('#datatable').bootstrapTable({
                data:result_table_dict,
                columns:columns,
                striped: true,
                pagination: true,
                showColumns: true,
                showToggle: false,
                showExport: true,
                sortable: true,
                paginationVAlign: 'both',
                pageSize: 10,
                pageList: [10, 25, 50, 100, 'ALL'],
            });
        };



    });







</script>




{% endblock%}